spring:
  profiles:
    active: real

  member-datasource:
    driverClassName: org.h2.Driver
    jdbc-url: jdbc:h2:mem:memberdb
    username: sa
    password:
  order-datasource:
    driverClassName: org.h2.Driver
    jdbc-url: jdbc:h2:mem:orderdb
    username: sa
    password:



logging:
  level:
    #org.hibernate.type: trace
    org.hibernate.sql: debug
#
server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
