spring:

  #JPA 셋팅
  memberms-jpa:
    properties:
      hibernate:
        format_sql: false
    show_sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
  orderms-jpa:
    properties:
      hibernate:
        format_sql: false
    show_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  #DataSource 셋팅
  memberms-datasource:
    driverClassName: org.h2.Driver
    jdbc-url: jdbc:h2:mem:memberMsRealDb;MODE=MySQL
    username: sa
    password:
  orderms-datasource:
    driverClassName: org.h2.Driver
    jdbc-url: jdbc:h2:mem:orderMsRealDb;MODE=PostgreSQL
    username: sa
    password:

logging:
  level:
    root: info
    org.hibernate.type: info
    org.hibernate.sql: info

