spring:

  #JPA 셋팅
  memberms-jpa:
    properties:
      hibernate:
        format_sql: true
    show_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  orderms-jpa:
    properties:
      hibernate:
        format_sql: true
    show_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  #DataSource Setting
  memberms-datasource:
    driverClassName: org.h2.Driver
    jdbc-url: jdbc:h2:mem:memberMsDevDb;MODE=MySQL
    username: sa
    password:
  orderms-datasource:
    driverClassName: org.h2.Driver
    jdbc-url: jdbc:h2:mem:orderMsDevDb;MODE=PostgreSQL
    username: sa
    password:


logging:
  level:
    root: info
    org.hibernate.type: info
    org.hibernate.sql: info

